name: airbnb_clone

description: Flutter clone de Airbnb — Explore + Wishlists (proyecto universitario)

publish_to: 'none'

version: 0.3.0+3


environment:

  sdk: '>=3.3.0 <4.0.0'

  flutter: '>=3.19.0'


dependencies:

  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.6

  google_fonts: ^6.1.0        # Inter Variable (sustituto open-source de Airbnb Cereal)

  cached_network_image: ^3.3.1 # Imágenes con caché en memoria + disco


dev_dependencies:

  flutter_test:

    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true